var chker = require("../routes/component/check/checker");

function testChk(){
	var a;
	var params = {e:true,w:true,f:10};
	console.info(chker.check(null, '测试', params));
	console.info(chker.check('', '测试', params));
	console.info(chker.check('  ', '测试', params));
	console.info(chker.check(a, '测试', params));
	console.info(chker.check(0, '测试', params));
	console.info(chker.check(0.0, '测试', params));
	console.info(chker.check('一个网管呃一个网管呃一个网管呃', '测试', params));
	console.info(chker.check("一个网管呃一个'网管\\呃一个网管呃", '测试', params));
	console.info("****************************");
	params = {f:2};
	console.info(chker.check('', '测试', params));
	console.info(chker.check('  ', '测试', params));
	console.info(chker.check(0.0, '测试', params));
	console.info(chker.check('0.0', '测试', params));
	console.info(chker.check('一个网管呃一个网管呃一个网管呃', '测试', params));
	console.info(chker.check("一个网管呃一个'网管\\呃一个网管呃", '测试', params));
	params = {n:true,f:10};
	console.info(chker.check('一个网管呃一个网管呃一个网管呃', '测试', params));
	console.info(chker.check(7889, '测试2', params));
	console.info(chker.check(7889.23, '测试2', params));
	console.info(chker.check(-7889, '测试2', params));
	console.info(chker.check(-7889.266, '测试2', params));
	console.info(chker.check(0, '测试2', params));
	console.info(chker.check(-0, '测试2', params));
	console.info(chker.check(0.0, '测试2', params));
	console.info(chker.check(-0.0, '测试2', params));
	console.info(chker.check('7889', '测试2', params));
	console.info(chker.check('7889.23', '测试2', params));
	console.info(chker.check('-7889', '测试2', params));
	console.info(chker.check('-7889.266', '测试2', params));
	console.info(chker.check('0', '测试2', params));
	console.info(chker.check('-0', '测试2', params));
	console.info(chker.check('0.0', '测试2', params));
	console.info(chker.check('-0.0', '测试2', params));
	console.info(chker.check('--0.0', '测试2', params));
	console.info(chker.check('-0a.0', '测试2', params));
	console.info(chker.check('.0', '测试2', params));
	console.info(chker.check('-0.', '测试2', params));
	console.info(chker.check('-0.a', '测试2', params));
	console.info(chker.check('-.0', '测试2', params));
	console.info("-----------------------------");
	params = {n:true,fi:5,fd:0};
	console.info(chker.check(a, '测试2', params));
	console.info(chker.check(7889, '测试2', params));
	console.info(chker.check(78890, '测试2', params));
	console.info(chker.check(-7889, '测试2', params));
	console.info(chker.check(-78890, '测试2', params));
	console.info(chker.check(788900, '测试2', params));
	console.info(chker.check(-788900, '测试2', params));
	console.info(chker.check(-788900.0, '测试2', params));
	console.info(chker.check('7889', '测试2', params));
	console.info(chker.check('78890', '测试2', params));
	console.info(chker.check('-7889', '测试2', params));
	console.info(chker.check('-78890', '测试2', params));
	console.info(chker.check('788900', '测试2', params));
	console.info(chker.check('-788900', '测试2', params));
	console.info(chker.check('-788900.0', '测试2', params));
	console.info("-------------日期检查----------------");
	params = {d:true};
	console.info(chker.check(a,'测试2', params));
	console.info(chker.check(null,'测试2', params));
	console.info(chker.check("",'测试2', params));
	console.info(chker.check("      ",'测试2', params));
	console.info(chker.check("2016-12-12",'测试2', params));
	console.info(chker.check("2016-13-12",'测试2', params));
	console.info(chker.check("2016-1-12",'测试2', params));
	console.info(chker.check("2016-12",'测试2', params));
	console.info(chker.check("2016-01-12",'测试2', params));
	console.info(chker.check("2016-01-2",'测试2', params));
	console.info(chker.check("2016-02-29",'测试2', params));
	console.info(chker.check("2014-02-29",'测试2', params));
	console.info(chker.check("2016/02/29",'测试2', params));
	console.info(chker.check("2014/02/29",'测试2', params));
	console.info(chker.check("2014/1/29",'测试2', params));
	console.info(chker.check("20140129",'测试2', params));
	console.info(chker.check("20141/29",'测试2', params));
	console.info(chker.check("2014//",'测试2', params));
	console.info(chker.check("2014/1/1",'测试2', params));
	console.info(chker.check("2014/1/100",'测试2', params));
}

testChk();